services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      TZ: "Australia/Melbourne"
      EULA: "TRUE"
      SERVER_NAME: "JK1-GNOCCHI"
      MOTD: |
        \u00A79Chill vibes for chill miners\u00A7r
        \u00A78Recommended mods: Sodium, Xaero's Minimap
      VERSION: "1.21.6"
      RCON_CMDS_STARTUP: |-
        gamerule keepInventory true
        gamerule maxEntityCramming 0
      RCON_PASSWORD: "RCONAdmin2024!"
      DIFFICULTY: "hard"
      MAX_PLAYERS: "10"
      FORCE_GAMEMODE: "true"
      ALLOW_FLIGHT: "false"
      GAMEMODE: "survival"
      SPAWN_PROTECTION: "0"
      MEMORY: "12G"
      TYPE: "FABRIC"
      MODRINTH_PROJECTS: |
        fabric-api
        fabric-language-kotlin
        lithium
        ferrite-core
        spark
        death-counter
        fallingtree
        appleskin
      SYNC_CHUNK_WRITES: "FALSE"
      SIMULATION_DISTANCE:  "5"
      VIEW_DISTANCE: "18"
      LOG_TIMESTAMP: "true"
      OPS: |
        m1nefury
      WHITELIST: |
        kelvinferd
        jferdy
        sosiskeju
        har0bed
        clarencedude
    volumes:
      - ./minecraft-data:/data
    restart: 'unless-stopped'