services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      SERVER_NAME: "Kwe-san"
      MOTD: "Welcome! Chill vibes for chill miners :)"
      DIFFICULTY: "hard"
      MAX_PLAYERS: "10"
      FORCE_GAMEMODE: "true"
      ALLOW_FLIGHT: "false"
      GAMEMODE: "survival"
      SPAWN_PROTECTION: "0"
    volumes:
      - minecraft-data:/data
    restart: 'unless-stopped'

volumes:
  minecraft-data:
    external: true

